# Generated by Django 3.1.7 on 2022-12-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karoRecharge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='rechargePlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagesRP', to='karoRecharge.rechargeplan'),
        ),
    ]
