# Generated by Django 3.1.7 on 2022-12-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karoRecharge', '0002_images_rechargeplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargeplan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
