# Generated by Django 3.1.7 on 2022-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karoRecharge', '0003_rechargeplan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='File'),
        ),
    ]
