# Generated by Django 3.1.7 on 2022-12-13 05:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('karoRecharge', '0004_auto_20221212_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rechargeplan',
            options={'verbose_name_plural': 'Prepaid Recharge Plan List'},
        ),
        migrations.CreateModel(
            name='generateCustomerRecharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(blank=True, max_length=256, null=True)),
                ('customerNumber', models.BigIntegerField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('customerPlan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerPlanCMN', to='karoRecharge.rechargeplan')),
            ],
            options={
                'verbose_name_plural': 'Generated recharge List : Customer Numbers',
            },
        ),
    ]
