# Generated by Django 3.1.7 on 2022-12-13 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karoRecharge', '0005_auto_20221213_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='rechargePlan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagesRP', to='karoRecharge.rechargeplan'),
        ),
    ]
