# Generated by Django 3.1.7 on 2022-12-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karoRecharge', '0006_auto_20221213_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecustomerrecharge',
            name='customerPlan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
