# Generated by Django 3.1.7 on 2022-12-13 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karoRecharge', '0007_auto_20221213_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecustomerrecharge',
            name='customerPlan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerPlanCMN', to='karoRecharge.rechargeplan'),
        ),
    ]
